server:
  port: 9080
spring:
  application:
    name: microservice-a
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
  rabbitmq:
    username: user
    password: user
management:
  endpoints:
    web:
      exposure:
        include: "*"

